### ISSUE TITLE
MediaWiki Integration

### ISSUE THREAD

**Issue by bencevans** [somakeit/members-area#1]
MediaWiki integration look's like it'll be manageable. 

I see that we have 2 options:
#### OpenID

There's already a MediaWiki [Plugin](http://www.mediawiki.org/wiki/Extension:OpenID) for OpenID authentication so we can write an OpenID interface for the members-area.

_(I prefer this method as proven and we can use OpenID for any other SoutHACKton projects & of course identification for other things across the internetz)_
#### Custom MediaWiki Plugin

The authentication in MediaWiki is extendable by writing 2 Classes that match their internal API. The Classes are [AuthPlugin](http://svn.wikimedia.org/doc/classAuthPlugin.html) & [AuthPluginUser](http://svn.wikimedia.org/doc/classAuthPluginUser.html).

Before we can write the class we need some method to check the username/password on the members-area in the form of an API.

The API would probably need to be limited to either a specific IP (of VPS) else at least rate limited to stop brute-forcing etc.

I've not looked at how your hashing/encrypting passwords but I'd suggest we don't send plain-text passwords and hash/encrypt on the MediaWiki end.

[MediaWiki Example Layout](http://svn.wikimedia.org/viewvc/mediawiki/trunk/phase3/includes/AuthPlugin.php?view=markup)

/cc @benjie

**Comment by bencevans** [comment]
`openid` [npm](https://npmjs.org/package/openid) ([graph](http://npmgraph.bensbit.co.uk/package/openid)) [github](https://github.com/havard/node-openid)

**Comment by benjie** [comment]
Cool. Should be relatively easy to split the code from [routes/user.coffee line 24-36](https://github.com/so-make-it/members-area/blob/71d4f9dfe26c3c2745d724b15c065f8e42019e33/routes/user.coffee#L24) into a separate handler - that's the bit that does auth. Effectively it has three error types: (1) database or other error, (2) couldn't find you or your password doesn't match, (3) you've not been approved yet. You should [add this as a sequelize classMethod](http://www.sequelizejs.com/#models-expansion) on the User model.

Rate limiting password attempts is a good idea - I'd just do it with shared state.

By the way, you should be able to tweak the code to optionally use a SQLITE database instead of MySQL to make local dev easier. May be worth doing to make it easier for others to contribute.

I like the idea of having members.somakeit.org.uk/p/Benjie (or similar) be an OpenID URL, so that's a good plan too. Would it be worth splitting these things into separate issues?

I'm working on password resetting and then the admin features like approving users.

G2g!

**Comment by benjie** [comment]
Whoops.

**Comment by bencevans** [comment]
@benjie turns out OpenID is a bitch, there's no node base OpenID provider module or example on GitHub, looking at the specification it's going to take a lot of time which uncomfortably I can't commit to atm.

Another option is OAuth which is quite a bit easier than OpenID to implement.

Thoughts?

**Comment by benjie** [comment]
I don't really care what's used so long as it gets the job done, is secure, and doesn't cause the users (or administrators) too much of a headache. I think the simplest might just to sync the members.somakeit and wiki.somakeit usernames/passwords as appropriate, but I fear that'd get messy over time. OAuth1.0a would be just fine. Probably best not to use OAuth2 for various reasons. 

I might look into this myself soon as I want this integration within the next 2 weeks if possible and I don't want to put any pressure on you!

**Comment by benjie** [comment]
Forgot to close this; did it 6 months ago with https://github.com/so-make-it/mediawiki-extension
